### ISSUE TITLE
Attribute Views

### ISSUE THREAD

**Issue by amarcionek** [Upplication/Amazon-S3-FileSystem-NIO2#67]
Is there a reason why S3FileSystem.supportedFileAttributeViews() returns "basic" but S3FileSystemProvider.getFileAttributeView throws UnsupportedOperationException?  It seems to me that if you're going to say you support a view, you should support it.  I suppose I get that someone may use the former to determine if one could call S3FileSystemProvider.readAttributes, but that doesn't seem quite right.

**Comment by jarnaiz** [comment]
Hi @amarcionek 

There isnt any reason, I just forgot it :/
At first i was not going to develop any kind of feature for querying ACLs but some users suggests me some basic implementation and now the library have posix and basic ACLs :)
In the 1.5.3 version this issue is solved.

Im not going to implement the "modify ACL feature" for now... maybe the next weekend but im not sure, so if you want to add this feature and improve the code, I will appreciate it very much.

Cheers!
